org: vicchai
app: naksin
service: nakvaksin

frameworkVersion: '2'

provider:
    name: aws
    runtime: nodejs12.x
    lambdaHashingVersion: '20201221'
    region: ap-southeast-1

functions:
    # hello:
    #     handler: hello-api/handler.hello
    #     events:
    #         - http:
    #               path: /
    #               method: get

    getUserInfo:
        handler: user/handler.getUserInfo
        events:
            - http:
                  path: getuserinfo
                  method: post
