org: vicchai
app: naksin
service: nakvaksin

frameworkVersion: '2'

plugins:
    - serverless-webpack
    - serverless-iam-roles-per-function

provider:
    name: aws
    runtime: nodejs12.x
    lambdaHashingVersion: 20201221
    region: ap-southeast-1

functions:
    getUserInfo:
        handler: users/handler.getUserInfo
        events:
            - httpApi:
                  path: /getuserinfo
                  method: GET
    processPreUserQueue:
        handler: users/handler.processPreUserQueue
        # batchSize: 10
        # reservedConcurrency: 10
        events:
            - sqs:
                  arn:
                      Fn::GetAtt:
                          - PreUserQueue
                          - Arn
    pushUserToQueue:
        handler: users/pushUserToQueue.handler
        environment:
            PreUserQueue_URL: { Ref: PreUserQueue }
        iamRoleStatements:
            - Effect: 'Allow'
              Action:
                  - sqs:SendMessage
              Resource:
                  Fn::GetAtt:
                      - PreUserQueue
                      - Arn

resources:
    Resources:
        PreUserQueue:
            Type: 'AWS::SQS::Queue'
            Properties:
                QueueName: 'PreUserQueue'
